### ISSUE TITLE
Lint-based pubspec file

### ISSUE THREAD

**Issue by pattobrien** [pattobrien/sidecar#7]
Proposed pubspec file format:

```yaml
name: riverpod_avoid_stateful_widgets
publish_to: cloudsmith.io/riverpod
version: 0.1.0
micropub: sidecar

environment:
  sdk: ">=2.17.5 <3.0.0"

sidecar:
  type: lint

dependencies:
  riverpod_lint_utils: 0.1.0
  sidecar: ^0.1.0
```
